use axum::{
    body::Body,
    extract::State,
    http::{Request, StatusCode},
    middleware::Next,
    response::{IntoResponse, Response},
    Json,
};
use chrono::{DateTime, Utc};
use mongodb::{
    bson::{doc, oid::ObjectId, DateTime as BsonDateTime},
    Collection,
};
use rand::TryRngCore;
use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};
use subtle::ConstantTimeEq;

use crate::state::AppState;

pub const API_KEYS_COLLECTION: &str = "_api_keys";
pub const KEY_PREFIX: &str = "da_";
const KEY_RANDOM_BYTES: usize = 16;

/// MongoDB representation of an API key. The plaintext key is never stored;
/// only its SHA-256 hash. The `prefix` is purely cosmetic for the dashboard.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ApiKey {
    #[serde(rename = "_id", skip_serializing_if = "Option::is_none")]
    pub id: Option<ObjectId>,
    pub label: String,
    pub prefix: String,
    pub hash: String,
    pub created_at: BsonDateTime,
    #[serde(default)]
    pub last_used_at: Option<BsonDateTime>,
    #[serde(default)]
    pub revoked_at: Option<BsonDateTime>,
}

/// Generate a fresh, cryptographically random API key in the form
/// `da_<32 hex chars>`. The plaintext is returned and is the only chance
/// the caller has to see it.
pub fn generate_key() -> String {
    let mut bytes = [0u8; KEY_RANDOM_BYTES];
    rand::rngs::OsRng
        .try_fill_bytes(&mut bytes)
        .expect("OS RNG must succeed");
    format!("{}{}", KEY_PREFIX, hex::encode(bytes))
}

pub fn hash_key(plain: &str) -> String {
    let mut hasher = Sha256::new();
    hasher.update(plain.as_bytes());
    hex::encode(hasher.finalize())
}

/// First N characters that are safe to display on the dashboard.
pub fn display_prefix(plain: &str) -> String {
    plain.chars().take(KEY_PREFIX.len() + 6).collect()
}

pub fn keys_collection(state: &AppState) -> Collection<ApiKey> {
    state.db.collection::<ApiKey>(API_KEYS_COLLECTION)
}

/// Persist a new key (returning the inserted record). The plaintext is NOT
/// stored — caller is responsible for surfacing it once.
pub async fn insert_key(
    state: &AppState,
    plain: &str,
    label: &str,
) -> Result<ApiKey, mongodb::error::Error> {
    let now = BsonDateTime::from_chrono(Utc::now());
    let mut record = ApiKey {
        id: None,
        label: label.to_string(),
        prefix: display_prefix(plain),
        hash: hash_key(plain),
        created_at: now,
        last_used_at: None,
        revoked_at: None,
    };
    let inserted = keys_collection(state).insert_one(&record).await?;
    record.id = inserted.inserted_id.as_object_id();
    Ok(record)
}

/// What `ensure_bootstrap_key` did on this run, so the caller can pick the
/// right log message.
#[derive(Debug, Clone)]
pub enum BootstrapOutcome {
    /// A fresh, auto-generated key was inserted because the database was
    /// empty and no seed was supplied.
    AutoGenerated(String),
    /// The supplied `BOOTSTRAP_API_KEY` was inserted (DB was empty, or the
    /// seed wasn't already an active key).
    SeedInserted(String),
    /// The supplied `BOOTSTRAP_API_KEY` was previously revoked and has now
    /// been un-revoked, so it works again.
    SeedReinstated(String),
    /// The supplied `BOOTSTRAP_API_KEY` is already an active key; nothing
    /// changed.
    SeedAlreadyActive,
    /// Nothing to do — DB has at least one active key and no seed supplied.
    NoOp,
}

/// Reconcile the `_api_keys` collection with the optional `BOOTSTRAP_API_KEY`
/// seed.
///
/// Behaviour:
/// * If a non-empty seed is supplied, it is **always** honoured: inserted
///   when missing, un-revoked when revoked. This is what operators expect
///   when they put a value in the environment panel — it should "just work"
///   on the next deploy regardless of database state.
/// * If no seed is supplied and the DB has no active keys, a random key is
///   generated and inserted so the dashboard is reachable on first boot.
/// * If no seed is supplied and the DB already has active keys, this is a
///   no-op.
pub async fn ensure_bootstrap_key(
    state: &AppState,
    seed_plain: Option<String>,
) -> anyhow::Result<BootstrapOutcome> {
    let coll = keys_collection(state);

    let seed = seed_plain.and_then(|s| {
        let t = s.trim();
        if t.is_empty() { None } else { Some(t.to_string()) }
    });

    if let Some(plain) = seed {
        let hash = hash_key(&plain);
        let existing = coll.find_one(doc! { "hash": &hash }).await?;
        return match existing {
            Some(record) if record.revoked_at.is_none() => Ok(BootstrapOutcome::SeedAlreadyActive),
            Some(record) => {
                if let Some(id) = record.id {
                    coll.update_one(
                        doc! { "_id": id },
                        doc! { "$set": { "revoked_at": null } },
                    )
                    .await?;
                }
                Ok(BootstrapOutcome::SeedReinstated(plain))
            }
            None => {
                insert_key(state, &plain, "bootstrap").await?;
                Ok(BootstrapOutcome::SeedInserted(plain))
            }
        };
    }

    let active = coll
        .count_documents(doc! { "revoked_at": { "$eq": null } })
        .await?;
    if active > 0 {
        return Ok(BootstrapOutcome::NoOp);
    }

    let plain = generate_key();
    insert_key(state, &plain, "bootstrap").await?;
    Ok(BootstrapOutcome::AutoGenerated(plain))
}

/// Look up an active key by plaintext. Returns the matching record on
/// success. Uses constant-time comparison on the hash to avoid leaking
/// timing information across keys.
pub async fn verify_request_key(state: &AppState, plain: &str) -> Option<ApiKey> {
    let hash = hash_key(plain);
    let coll = keys_collection(state);
    let record = coll
        .find_one(doc! {
            "hash": &hash,
            "revoked_at": { "$eq": null },
        })
        .await
        .ok()
        .flatten()?;

    // Defence-in-depth: even though MongoDB returned a hit, do an explicit
    // constant-time hash compare before accepting the key.
    if record.hash.as_bytes().ct_eq(hash.as_bytes()).into() {
        Some(record)
    } else {
        None
    }
}

/// Best-effort fire-and-forget update of last_used_at. We don't want to add
/// latency to authenticated requests, so any error is logged and ignored.
pub fn touch_last_used(state: AppState, hash: String) {
    tokio::spawn(async move {
        let now = BsonDateTime::from_chrono(Utc::now());
        let res = keys_collection(&state)
            .update_one(
                doc! { "hash": &hash },
                doc! { "$set": { "last_used_at": now } },
            )
            .await;
        if let Err(e) = res {
            tracing::debug!(error = %e, "failed to update last_used_at");
        }
    });
}

fn extract_key(req: &Request<Body>) -> Option<String> {
    let headers = req.headers();
    if let Some(v) = headers.get("x-api-key").and_then(|h| h.to_str().ok()) {
        let trimmed = v.trim();
        if !trimmed.is_empty() {
            return Some(trimmed.to_string());
        }
    }
    if let Some(v) = headers
        .get(axum::http::header::AUTHORIZATION)
        .and_then(|h| h.to_str().ok())
    {
        let v = v.trim();
        if let Some(rest) = v.strip_prefix("Bearer ").or_else(|| v.strip_prefix("bearer ")) {
            let rest = rest.trim();
            if !rest.is_empty() {
                return Some(rest.to_string());
            }
        }
    }
    None
}

fn unauthorized(message: &str) -> Response {
    let body = Json(serde_json::json!({
        "error": "unauthorized",
        "message": message,
    }));
    let mut resp = (StatusCode::UNAUTHORIZED, body).into_response();
    resp.headers_mut().insert(
        "WWW-Authenticate",
        "Bearer realm=\"dump-anything\"".parse().unwrap(),
    );
    resp
}

/// Axum middleware that enforces a valid API key on the wrapped routes.
pub async fn require_api_key(
    State(state): State<AppState>,
    req: Request<Body>,
    next: Next,
) -> Response {
    let Some(plain) = extract_key(&req) else {
        return unauthorized("missing api key");
    };
    match verify_request_key(&state, &plain).await {
        Some(key) => {
            touch_last_used(state.clone(), key.hash.clone());
            next.run(req).await
        }
        None => unauthorized("invalid or revoked api key"),
    }
}

/// Convenience for the bootstrap path: turn a stored ApiKey into the
/// metadata-only public projection.
#[derive(Debug, Serialize)]
pub struct ApiKeyView {
    pub id: String,
    pub label: String,
    pub prefix: String,
    pub created_at: DateTime<Utc>,
    pub last_used_at: Option<DateTime<Utc>>,
    pub revoked_at: Option<DateTime<Utc>>,
}

impl From<ApiKey> for ApiKeyView {
    fn from(k: ApiKey) -> Self {
        Self {
            id: k
                .id
                .map(|o| o.to_hex())
                .unwrap_or_else(|| String::from("?")),
            label: k.label,
            prefix: k.prefix,
            created_at: k.created_at.to_chrono(),
            last_used_at: k.last_used_at.map(|d| d.to_chrono()),
            revoked_at: k.revoked_at.map(|d| d.to_chrono()),
        }
    }
}

pub async fn list_keys(state: &AppState) -> Result<Vec<ApiKeyView>, mongodb::error::Error> {
    use futures::TryStreamExt;
    let mut cursor = keys_collection(state)
        .find(doc! {})
        .sort(doc! { "created_at": -1 })
        .await?;
    let mut out = Vec::new();
    while let Some(k) = cursor.try_next().await? {
        out.push(k.into());
    }
    Ok(out)
}

pub async fn revoke_key(
    state: &AppState,
    id: &ObjectId,
) -> Result<bool, mongodb::error::Error> {
    let now = BsonDateTime::from_chrono(Utc::now());
    let res = keys_collection(state)
        .update_one(
            doc! { "_id": id, "revoked_at": { "$eq": null } },
            doc! { "$set": { "revoked_at": now } },
        )
        .await?;
    Ok(res.modified_count > 0)
}

/// Helper: extract a hex ObjectId from a path segment, returning a typed
/// error if the value is malformed.
pub fn parse_object_id(s: &str) -> Result<ObjectId, crate::error::ApiError> {
    ObjectId::parse_str(s).map_err(|_| crate::error::ApiError::InvalidId(s.to_string()))
}

/// Underscore prefix is reserved for internal collections like `_api_keys`.
pub fn is_reserved_collection(name: &str) -> bool {
    name.starts_with('_') || name == API_KEYS_COLLECTION
}
