use std::net::SocketAddr;

use anyhow::Context;
use tracing_subscriber::{fmt, prelude::*, EnvFilter};

mod auth;
mod error;
mod routes;
mod state;

#[tokio::main]
async fn main() -> anyhow::Result<()> {
    let _ = dotenvy::dotenv();

    tracing_subscriber::registry()
        .with(EnvFilter::try_from_default_env().unwrap_or_else(|_| EnvFilter::new("info")))
        .with(fmt::layer().with_target(false))
        .init();

    let mongo_uri = std::env::var("MONGODB_URI")
        .unwrap_or_else(|_| "mongodb://localhost:27017".to_string());
    let database_name =
        std::env::var("DATABASE_NAME").unwrap_or_else(|_| "dump_anything".to_string());

    let state = state::AppState::connect(&mongo_uri, &database_name)
        .await
        .context("failed to connect to MongoDB")?;

    let bootstrap_seed = std::env::var("BOOTSTRAP_API_KEY").ok();
    let outcome = auth::ensure_bootstrap_key(&state, bootstrap_seed)
        .await
        .context("failed to seed bootstrap api key")?;
    log_bootstrap_outcome(outcome);

    let app = routes::router(state);

    let host = std::env::var("HOST").unwrap_or_else(|_| "0.0.0.0".to_string());
    let port: u16 = std::env::var("PORT")
        .ok()
        .and_then(|p| p.parse().ok())
        .unwrap_or(3000);
    let addr: SocketAddr = format!("{host}:{port}").parse()?;

    tracing::info!(%addr, db = %database_name, "dump-anything api listening");
    let listener = tokio::net::TcpListener::bind(addr).await?;
    axum::serve(listener, app).await?;
    Ok(())
}

fn log_bootstrap_outcome(outcome: auth::BootstrapOutcome) {
    use auth::BootstrapOutcome::*;
    let banner = "=================== BOOTSTRAP API KEY ===================";

    match outcome {
        AutoGenerated(plain) => {
            tracing::warn!("{banner}");
            tracing::warn!("source: auto-generated (database was empty)");
            tracing::warn!("key:    {plain}");
            tracing::warn!("Save this now — it will not be shown again. Use it to log");
            tracing::warn!("into the dashboard, then create labelled keys from there.");
            tracing::warn!("=========================================================");
        }
        SeedInserted(plain) => {
            tracing::warn!("{banner}");
            tracing::warn!("source: BOOTSTRAP_API_KEY env (newly inserted)");
            tracing::warn!("key:    {plain}");
            tracing::warn!("This key is now active. Rotate or revoke once you have");
            tracing::warn!("created labelled keys from the dashboard.");
            tracing::warn!("=========================================================");
        }
        SeedReinstated(plain) => {
            tracing::warn!("{banner}");
            tracing::warn!("source: BOOTSTRAP_API_KEY env (un-revoked)");
            tracing::warn!("key:    {plain}");
            tracing::warn!("This key was previously revoked and has been re-activated");
            tracing::warn!("because the seed value matches an existing record.");
            tracing::warn!("=========================================================");
        }
        SeedAlreadyActive => {
            tracing::info!(
                "BOOTSTRAP_API_KEY matches an already-active key; no changes made"
            );
        }
        NoOp => {
            tracing::debug!("api keys exist; bootstrap skipped");
        }
    }
}
